#ifndef ATOMIC_NUM_C
#define ATOMIC_NUM_C
#define H_ATOM_NUM 1
#define He_ATOM_NUM 2
#define Li_ATOM_NUM 3
#define Be_ATOM_NUM 4
#define B_ATOM_NUM 5
#define C_ATOM_NUM 6
#define N_ATOM_NUM 7
#define O_ATOM_NUM 8
#define F_ATOM_NUM 9
#define Ne_ATOM_NUM 10
#define Na_ATOM_NUM 11
#define Mg_ATOM_NUM 12
#define Al_ATOM_NUM 13
#define Si_ATOM_NUM 14
#define P_ATOM_NUM 15
#define S_ATOM_NUM 16
#define Cl_ATOM_NUM 17
#define Ar_ATOM_NUM 18
#define K_ATOM_NUM 19
#define Ca_ATOM_NUM 20
#define Sc_ATOM_NUM 21
#define Ti_ATOM_NUM 22
#define V_ATOM_NUM 23
#define Cr_ATOM_NUM 24
#define Mn_ATOM_NUM 25
#define Fe_ATOM_NUM 26
#define Co_ATOM_NUM 27
#define Ni_ATOM_NUM 28
#define Cu_ATOM_NUM 29
#define Zn_ATOM_NUM 30
#define Ga_ATOM_NUM 31
#define Ge_ATOM_NUM 32
#define As_ATOM_NUM 33
#define Se_ATOM_NUM 34
#define Br_ATOM_NUM 35
#define Kr_ATOM_NUM 36
#define Rb_ATOM_NUM 37
#define Sr_ATOM_NUM 38
#define Y_ATOM_NUM 39
#define Zr_ATOM_NUM 40
#define Nb_ATOM_NUM 41
#define Mo_ATOM_NUM 42
#define Tc_ATOM_NUM 43
#define Ru_ATOM_NUM 44
#define Rh_ATOM_NUM 45
#define Pd_ATOM_NUM 46
#define Ag_ATOM_NUM 47
#define Cd_ATOM_NUM 48
#define In_ATOM_NUM 49
#define Sn_ATOM_NUM 50
#define Sb_ATOM_NUM 51
#define Te_ATOM_NUM 52
#define I_ATOM_NUM 53
#define Xe_ATOM_NUM 54
#define Cs_ATOM_NUM 55
#define Ba_ATOM_NUM 56
#define La_ATOM_NUM 57
#define Ce_ATOM_NUM 58
#define Pr_ATOM_NUM 59
#define Nd_ATOM_NUM 60
#define Pm_ATOM_NUM 61
#define Sm_ATOM_NUM 62
#define Eu_ATOM_NUM 63
#define Gd_ATOM_NUM 64
#define Tb_ATOM_NUM 65
#define Dy_ATOM_NUM 66
#define Ho_ATOM_NUM 67
#define Er_ATOM_NUM 68
#define Tm_ATOM_NUM 69
#define Yb_ATOM_NUM 70
#define Lu_ATOM_NUM 71
#define Hf_ATOM_NUM 72
#define Ta_ATOM_NUM 73
#define W_ATOM_NUM 74
#define Re_ATOM_NUM 75
#define Os_ATOM_NUM 76
#define Ir_ATOM_NUM 77
#define Pt_ATOM_NUM 78
#define Au_ATOM_NUM 79
#define Hg_ATOM_NUM 80
#define Tl_ATOM_NUM 81
#define Pb_ATOM_NUM 82
#define Bi_ATOM_NUM 83
#define Po_ATOM_NUM 84
#define At_ATOM_NUM 85
#define Rn_ATOM_NUM 86
#define Fr_ATOM_NUM 87
#define Ra_ATOM_NUM 88
#define Ac_ATOM_NUM 89
#define Th_ATOM_NUM 90
#define Pa_ATOM_NUM 91
#define U_ATOM_NUM 92
#define Np_ATOM_NUM 93
#define Pu_ATOM_NUM 94
#define Am_ATOM_NUM 95
#define Cm_ATOM_NUM 96
#define Bk_ATOM_NUM 97
#define Cf_ATOM_NUM 98
#define Es_ATOM_NUM 99
#define Fm_ATOM_NUM 100
#define Md_ATOM_NUM 101
#define No_ATOM_NUM 102
#define Lr_ATOM_NUM 103
#define Rf_ATOM_NUM 104
#define Db_ATOM_NUM 105
#define Sg_ATOM_NUM 106
#define Bh_ATOM_NUM 107
#define Hs_ATOM_NUM 108
#define Mt_ATOM_NUM 109
#define Ds_ATOM_NUM 110
#define Rg_ATOM_NUM 111
#define Cn_ATOM_NUM 112
#define Nh_ATOM_NUM 113
#define Fl_ATOM_NUM 114
#define Mc_ATOM_NUM 115
#define Lv_ATOM_NUM 116
#define Ts_ATOM_NUM 117
#define Og_ATOM_NUM 118
#endif